apiVersion: v1
data:
  BACKEND_ENABLED: "True"
  BACKEND_SERVICE: http://whereami-backend
  ECHO_HEADERS: "False"
  GRPC_ENABLED: "False"
  METADATA: frontend
kind: ConfigMap
metadata:
  labels:
    app: whereami-frontend
  name: whereami-configmap-frontend
  namespace: whereami
