apiVersion: v1
data:
  BACKEND_ENABLED: "False"
  BACKEND_SERVICE: http://whereami-backend
  ECHO_HEADERS: "False"
  GRPC_ENABLED: "False"
  METADATA: backend
kind: ConfigMap
metadata:
  labels:
    app: whereami-backend
  name: whereami-configmap-backend
